# Generated by Django 2.2.6 on 2021-09-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='array',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(default='ATCGATCG', max_length=50, verbose_name='输入序列')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
                ('result', models.TextField()),
            ],
            options={
                'verbose_name': 'array',
                'verbose_name_plural': 'array',
                'db_table': 'db_array',
            },
        ),
        migrations.CreateModel(
            name='svm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('body', models.FileField(upload_to='file_page', verbose_name='上传文件')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': 'svm',
                'verbose_name_plural': 'svm',
                'db_table': 'db_svm',
            },
        ),
    ]
